routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

/**
 * Public Routes
 */
Route::get('/', [
    'uses' => 'BlogController@index',
    'as'   => 'index',
]);

Route::get('/blog/{post}', [
    'uses' => 'BlogController@post',
    'as'   => 'blog.post',
    'middleware' => ['post.published'],
]);

Route::get('/blog/category/{category}', [
    'uses' => 'BlogController@category',
    'as'   => 'blog.category',
]);

Route::get('/blog/tag/{tag}', [
    'uses' => 'BlogController@tag',
    'as'   => 'blog.tag'
]);

Route::post('/blog/comment/{post}', [
    'uses' => 'BlogController@comment',
    'as'   => 'blog.comment'
]);

/**
 * Admin Routes
 */
Route::group([
    'namespace'  => '\\Admin',
    'middleware' => ['auth', 'admin.access'],
    'prefix'     => 'admin'
], function () {

    Route::group(['prefix' => 'posts'], function () {

        Route::get('/', [
            'uses' => 'PostController@index',
            'as'   => 'admin.posts.list'
        ]);

        Route::get('/create', [
            'uses' => 'PostController@create',
            'as'   => 'admin.posts.create'
        ]);

        Route::post('/', [
            'uses' => 'PostController@store',
            'as'   => 'admin.posts.store',
        ]);

        Route::get('/{post}', [
            'uses' => 'PostController@edit',
            'as'   => 'admin.posts.edit',
        ]);

        Route::patch('/{post}', [
            'uses' => 'PostController@update',
            'as'   => 'admin.posts.update',
        ]);

        Route::get('/{post}/remove', [
            'uses' => 'PostController@destroy',
            'as'   => 'admin.posts.remove',
        ]);

        Route::get('/{post}/publish', [
            'uses' => 'PostController@publish',
            'as'   => 'admin.posts.publish',
        ]);

        Route::get('/{post}/trash', [
            'uses' => 'PostController@trash',
            'as'   => 'admin.posts.trash',
        ]);

    });

    Route::group(['prefix' => 'categories'], function () {
        Route::get('/', [
            'uses' => 'CategoryController@index',
            'as'   => 'admin.categories.list',
        ]);

        Route::get('/create', [
            'uses' => 'CategoryController@create',
            'as'   => 'admin.categories.create',
        ]);

        Route::post('/', [
            'uses' => 'CategoryController@store',
            'as'   => 'admin.categories.store',
        ]);

        Route::get('/{category}', [
            'uses' => 'CategoryController@edit',
            'as'   => 'admin.categories.edit',
        ]);

        Route::patch('/{category}', [
            'uses' => 'CategoryController@update',
            'as'   => 'admin.categories.update',
        ]);

        Route::get('/{category}/remove', [
            'uses' => 'CategoryController@destroy',
            'as'   => 'admin.categories.remove',
        ]);
    });

    Route::group(['prefix' => 'tags'], function () {
        Route::get('/', [
            'uses' => 'TagController@index',
            'as'   => 'admin.tags.list',
        ]);

        Route::get('/create', [
            'uses' => 'TagController@create',
            'as'   => 'admin.tags.create',
        ]);

        Route::post('/', [
            'uses' => 'TagController@store',
            'as'   => 'admin.tags.store',
        ]);

        Route::get('/{tag}', [
            'uses' => 'TagController@edit',
            'as'   => 'admin.tags.edit',
        ]);

        Route::patch('/{tag}', [
            'uses' => 'TagController@update',
            'as'   => 'admin.tags.update',
        ]);

        Route::get('/{tag}/remove', [
            'uses' => 'TagController@destroy',
            'as'   => 'admin.tags.remove',
        ]);
    });

    Route::group(['prefix' => 'comments'], function () {
       Route::get('/', [
           'uses' => 'CommentController@index',
           'as'   => 'admin.comments.list',
       ]);

       Route::get('/{comment}/publish', [
           'uses' => 'CommentController@publish',
           'as'   => 'admin.comments.publish',
       ]);

       Route::get('/{comment}/spam', [
           'uses' => 'CommentController@spam',
           'as'   => 'admin.comments.spam',
       ]);

       Route::get('/{comment}/trash', [
           'uses' => 'CommentController@trash',
           'as'   => 'admin.comments.trash',
       ]);

       Route::get('/{comment}/remove', [
           'uses' => 'CommentController@destroy',
           'as'   => 'admin.comments.remove',
       ]);
    });
});

/**
 * API Routes
 */
Route::group([
    'namespace'  => '\\Api',
    'middleware' => [],
    'prefix'     => 'api',
], function () {

    Route::get('/posts', [
        'uses' => 'PostController@index',
        'as'   => 'api.posts.list'
    ]);

    Route::get('/categories', [
        'uses' => 'CategoryController@index',
        'as'   => 'api.categories.list',
    ]);

    Route::get('/tags', [
        'uses' => 'TagController@index',
        'as'   => 'api.tags.list',
    ]);

    Route::get('/comments', [
        'uses' => 'CommentController@index',
        'as'   => 'api.comments.list',
    ]);
});

app/Post.php
<?php

namespace App;

use App;
use App\Contracts\PostContract;
use App\Traits\HasStatus;
use App\Traits\TracksRecord;
use Illuminate\Database\Eloquent\Model;

/**
 * Class Post
 *
 * Core blog post model
 *
 * @package App
 */
class Post extends Model implements PostContract
{
    use HasStatus, TracksRecord;

    protected $fillable = ['status_id', 'title', 'slug', 'content', 'feature_label', 'video_link', 'publish_at', 'featured_image', 'gallery_images'];

    /**
     * Sets tablename for all child models
     *
     * @var string
     */
    protected $table = 'posts';

    /**
     * Defines fields expecting date objects
     *
     * @var array
     */
    protected $dates = ['created_at', 'updated_at', 'publish_at'];

    /**
     * Model events for setting type
     */
    protected static function boot()
    {
        parent::boot();

        static::creating(function (Post $post) {
            $post->type = get_class($post);
        });

        static::updating(function (Post $post) {
            $post->type = get_class($post);
        });
    }

    /**
     * Static function for returning a display type
     *
     * @return string
     */
    public function getTypeNameAttribute()
    {
        return 'Standard';
    }

    /**
     * Custom model override to support returning of different model types
     *
     * @param array $attributes
     * @param null $connection
     * @return static
     */
    public function newFromBuilder($attributes = [], $connection = null)
    {
        if (!isset($attributes->type)) {
            return parent::newFromBuilder($attributes, $connection);
        }

        $model = App::make($attributes->type)->newInstance([], true);
        $model->setRawAttributes((array) $attributes, true);
        $model->setConnection($connection ?: $this->connection);

        return $model;
    }

    /**
     * Override to set slug as route key for posts
     *
     * @return string
     */
    public function getRouteKeyName()
    {
        return 'slug';
    }

    /**
     * A blog can have many categtories
     *
     * @return \Illuminate\Database\Eloquent\Relations\BelongsToMany
     */
    public function categories()
    {
        return $this->belongsToMany('App\Category', 'post_categories', 'post_id', 'category_id');
    }

    /**
     * A blog can have many images
     *
     * @return \Illuminate\Database\Eloquent\Relations\BelongsToMany
     */
    public function images()
    {
        return $this->belongsToMany('App\Image', 'post_images')->withPivot('type', 'caption', 'ordinal');
    }

    /**
     * Posts may have many comments
     *
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function comments()
    {
        return $this->hasMany('App\Comment', 'post_id');
    }

    /**
     * A post can be associated with many tags
     *
     * @return \Illuminate\Database\Eloquent\Relations\BelongsToMany
     */
    public function tags()
    {
        return $this->belongsToMany('App\Tag', 'post_tags', 'post_id', 'tag_id');
    }

    /**
     * Returns a shortened content string
     *
     * @return string
     */
    public function getShortAttribute()
    {
        return str_limit(strip_tags($this->attributes['content']), 300);
    }

    /**
     * Returns a formatted display of the created date
     *
     * @return mixed
     */
    public function getDisplayDateAttribute()
    {
        return $this->created_at->format('M jS Y');
    }

    /**
     * Returns
     * @return string
     */
    public function getAuthorAttribute()
    {
        if (empty($this->createdBy)) {
            return 'Admin';
        }

        return $this->createdBy->name;
    }

    /**
     * Returns a count of post comments
     *
     * @return int
     */
    public function getCommentCountAttribute()
    {
        return $this->comments()->count();
    }

    /**
     * Returns additional validation rules for post type
     *
     * @return array
     */
    public function getValidationRules()
    {
        return [
            'featured_image' => 'required',
        ];
    }

    /**
     * Returns view for outputting feature
     *
     * @return string
     */
    public function getFeatureViewAttribute()
    {
        return 'includes.standard-post';
    }

    /**
     * Returns view for outputting feature summary
     * @return string
     */
    public function getFeatureShortViewAttribute()
    {
        return 'includes.standard-post-short';
    }
}

app/Http/Controllers/Admin/PostController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\PostRequest;
use App\Post;
use App\Services\PostManagerService;
use Session;

/**
 * Class PostController
 *
 * Post management interface
 *
 * @package App\Http\Controllers\Admin
 */
class PostController extends Controller
{

    /**
     * @var PostManagerService
     */
    protected $postManager;

    /**
     * PostController constructor.
     *
     * @param PostManagerService $postManager
     */
    public function __construct(PostManagerService $postManager)
    {
        $this->postManager = $postManager;
    }

    /**
     * Loads and displays post list
     */
    public function index()
    {
        return view('admin.posts.list');
    }

    /**
     * Displays post creation form
     */
    public function create()
    {
        return view('admin.posts.create')
            ->with('route', route('admin.posts.store'))
            ->with('method', 'post');
    }

    /**
     * Stores new posts
     */
    public function store(PostRequest $request)
    {
        $this->postManager->createPost($request->all());
        Session::flash('message', 'Post Created');
        return redirect()->route('admin.posts.list');
    }

    /**
     * Displays post edit form
     */
    public function edit(Post $post)
    {
        return view('admin.posts.edit')
            ->with('route', route('admin.posts.update', $post))
            ->with('method', 'patch')
            ->with('post', $post);
    }

    /**
     * Stores post updates
     */
    public function update(PostRequest $request, Post $post)
    {
        $this->postManager->updatePost($post, $request->all());
        Session::flash('message', 'Post Updated');
        return redirect()->route('admin.posts.list');
    }

    /**
     * Removes post from database
     */
    public function destroy(Post $post)
    {
        $this->postManager->getRepository()->deleteModel($post);
        Session::flash('message', 'Post Removed');
        return redirect()->route('admin.posts.list');
    }

    /**
     * Publishes provided post
     *
     * @param Post $post
     * @return \Illuminate\Http\RedirectResponse
     */
    public function publish(Post $post)
    {
        $this->postManager->updatePostStatus($post, 'published');
        Session::flash('message', 'Post Published');
        return redirect()->route('admin.posts.list');
    }

    /**
     * Trashes provided post
     *
     * @param Post $post
     * @return \Illuminate\Http\RedirectResponse
     */
    public function trash(Post $post)
    {
        $this->postManager->updatePostStatus($post, 'trash');
        Session::flash('message', 'Post Trashed');
        return redirect()->route('admin.posts.list');
    }
}

app/Http/Controllers/Api/PostController.php
<?php

namespace App\Http\Controllers\Api;

use App\Http\Controllers\Controller;
use App\Post;
use DataTables;
use Illuminate\Http\Request;

class PostController extends Controller
{
    public function index()
    {
        $query = Post::query();

        return DataTables::eloquent($query)
            ->removeColumn('slug')
            ->removeColumn('content')
            ->removeColumn('feature_label')
            ->removeColumn('video_link')
            ->removeColumn('created_by')
            ->removeColumn('updated_by')
            ->editColumn('type', function (Post $post) {
                return $post->typeName;
            })
            ->editColumn('status_id', function (Post $post) {
                return $post->status->name;
            })
            ->addColumn('action', 'tables.post-actions')
            ->toJson();
    }
}

resources/views/admin/posts/create.blade.php
@extends('layouts.app')

@section('page-title', 'New Post')

@section('headline', 'New Post')

@section('content')
    <div>
        @include('admin.posts.form')
    </div>
@append

resources/views/admin/posts/edit.blade.php
@extends('layouts.app')

@section('page-title', 'Edit Post')

@section('headline', 'Edit Post')

@section('content')
    <div>
        @include('admin.posts.form')
    </div>
@append

resources/views/admin/posts/form.blade.php
<div class="container" id="post-container" data-title="{{ isset($post) ? $post->title : null }}" data-slug="{{ isset($post) ? $post->slug : null }}" data-type="{{ isset($post) ? $post->type : array_keys($types)[0] }}">
    {!! Form::open(['url' => $route, 'class' => 'form', 'role' => 'form', 'method' => $method]) !!}
        <div class="row">
            <div class="col-md-8">
                @include('includes.form-messages')
                <div class="row">
                    <div class="col-md-12">
                        {!! Form::textField('title', 'Title', null, ['v-model' => 'title']) !!}
                        {!! Form::textField('slug', 'Slug', null, ['v-model' => 'slug']) !!}
                        <div class="form-group">
                            {!! Form::label('status_id', 'Status') !!}<br />
                            {!! Form::select('status_id', $statuses->pluck('name', 'id')->all(), isset($post) ? $post->status_id : null) !!}
                        </div>
                        <h3>Content</h3>
                        {!! Form::textarea('content', isset($post) ? $post->content : null, ['class' => 'form-control', 'id' => 'content']) !!}
                    </div>
                </div>
                <br />
                <div class="row" id="gallery" v-if="type === 'App\\GalleryPost'">
                    <div class="col-md-12">
                        {!! Form::textField('feature_label', 'Label', isset($post) ? $post->feature_label : null) !!}
                        {!! Form::label('gallery_images', 'Images') !!}<br />
                        <div class="input-group">
                            <span class="input-group-btn">
                                <a id="lfm-1" data-input="thumbnail-1" data-preview="holder-1" class="btn btn-primary">
                                    <i class="fa fa-picture-o"></i> Choose
                                </a>
                            </span>
                            <input id="thumbnail-1" class="form-control" type="text" name="gallery_images[]">
                        </div>
                        <img id="holder-1" style="margin-top:15px;max-height:100px;"><Br />
                        <br />
                        <div class="input-group">
                            <span class="input-group-btn">
                                <a id="lfm-2" data-input="thumbnail-2" data-preview="holder-2" class="btn btn-primary">
                                    <i class="fa fa-picture-o"></i> Choose
                                </a>
                            </span>
                            <input id="thumbnail-2" class="form-control" type="text" name="gallery_images[]">
                        </div>
                        <img id="holder-2" style="margin-top:15px;max-height:100px;"><br />
                        <br />
                        <div class="input-group">
                            <span class="input-group-btn">
                                <a id="lfm-3" data-input="thumbnail-3" data-preview="holder-3" class="btn btn-primary">
                                    <i class="fa fa-picture-o"></i> Choose
                                </a>
                            </span>
                            <input id="thumbnail-3" class="form-control" type="text" name="gallery_images[]">
                        </div>
                        <img id="holder-3" style="margin-top:15px;max-height:100px;">
                    </div>
                </div>

                <div class="row" id="video" v-if="type === 'App\\VideoPost'">
                    <div class="col-md-12">
                        {!! Form::textField('feature_label', 'Label', isset($post) ? $post->feature_label : null) !!}
                        {!! Form::textField('video_link', 'Video Link', isset($post) ? $post->video_link : null) !!}
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-12">
                        <button type="submit" class="btn btn-primary btn-addon">
                            <i class="fa fa-save"></i> Save
                        </button>
                        <a class="btn btn-default" href="{{ route('admin.posts.list') }}">Cancel</a>
                    </div>
                </div>
            </div>
            <div class="col-md-4">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        Publish At
                    </div>
                    <div class="panel-body">
                        <div class="form-group">
                            {!! Form::label('publish_at', 'Publish this post at the following date/time') !!}<br />
                            {!! Form::datetime('publish_at', isset($post) ? $post->publish_at : null) !!}
                        </div>
                    </div>
                </div>
                <div class="panel panel-default">
                    <div class="panel-heading">
                        Format
                    </div>
                    <div class="panel-body">
                        @if(isset($post))
                            {{ $post->type_name }}
                        @else 
                            @foreach($types as $class => $type)
                                <input type="radio" name="type" id="post-format-{{ strtolower($type) }}" value="{{ $class }}" v-model="type" @if($type == 'Gallery') onclick="setTimeout(fileManagerSetup, 1000)" @endif/>
                                {!! Form::label('post-format-' . strtolower($type), $type) !!} <br />
                            @endforeach
                        @endif
                    </div>
                </div>
                <div class="panel panel-default">
                    <div class="panel-heading">
                        Categories
                    </div>
                    <div class="panel-body">
                        @foreach($categories as $category)
                            {!! Form::checkbox('categories[]', $category->id, (isset($post) && $post->categories->pluck('id')->contains($category->id)), ['id' => 'category-' . $category->id]) !!}
                            {!! Form::label('category-' . $category->id, $category->name) !!} <br />
                        @endforeach
                    </div>
                </div>
                <div class="panel panel-default">
                    <div class="panel-heading">
                        Tags
                    </div>
                    <div class="panel-body">
                        @foreach($tags as $tag)
                            {!! Form::checkbox('tags[]', $tag->id, (isset($post) && $post->tags->pluck('id')->contains($tag->id)), ['id' => 'tag-' . $tag->id]) !!}
                            {!! Form::label('tag-' . $tag->id, $tag->name) !!} <br />
                        @endforeach
                    </div>
                </div>
                <div class="panel panel-default">
                    <div class="panel-heading">
                        Featured Image
                    </div>
                    <div class="panel-body">
                        <div class="input-group">
                            <span class="input-group-btn">
                                <a id="lfm" data-input="thumbnail" data-preview="holder" class="btn btn-primary">
                                    <i class="fa fa-picture-o"></i> Choose
                                </a>
                            </span>
                            <input id="thumbnail" class="form-control" type="text" name="featured_image">
                        </div>
                        <img id="holder" style="margin-top:15px;max-height:100px;">
                    </div>
                </div>
            </div>
        </div>
    {!! Form::close() !!}
</div>
@section('script-src')
    {!! Html::script('js/ckeditor/ckeditor.js') !!}
    {!! Html::script('vendor/laravel-filemanager/js/lfm.js') !!}
@append
@section('scripts')
    <script>
        var options = {
            filebrowserImageBrowseUrl: '/laravel-filemanager?type=Images',
            filebrowserImageUploadUrl: '/laravel-filemanager/upload?type=Images&_token=',
            filebrowserBrowseUrl: '/laravel-filemanager?type=Files',
            filebrowserUploadUrl: '/laravel-filemanager/upload?type=Files&_token='
        };
        CKEDITOR.replace( 'content', options );

        var fileManagerSetup = function (event) {
            $('#lfm-1').filemanager('image');
            $('#lfm-2').filemanager('image');
            $('#lfm-3').filemanager('image');
        }

        $(document).ready(function() {
            $('#lfm').filemanager('image');
        });
    </script>
@append

resources/views/admin/posts/list.blade.php
@extends('layouts.app')

@section('page-title', 'Posts Admin')

@section('headline', 'Posts Admin')

@section('content')
    <div>
        <a class="btn btn-primary" href="{{ route('admin.posts.create') }}">New Post</a>
    </div>
    <table class="table table-bordered" id="posts-table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Type</th>
                <th>Status</th>
                <th>Title</th>
                <th>Created At</th>
                <th>Updated At</th>
                <th>Actions</th>
            </tr>
        </thead>
    </table>
@append
@section('css-src')
    <link href="{{ asset('css/jquery.dataTables.css') }}" rel="stylesheet">
@append
@section('script-src')
    <script src="{{ asset('js/jquery.dataTables.js') }}"></script>
@append
@section('scripts')
<script>
    $(function() {
        $('#posts-table').DataTable({
            processing: true,
            serverSide: true,
            ajax: '{!! route('api.posts.list') !!}',
            columns: [
                {data: 'id', name: 'id'},
                {data: 'type', name: 'type'},
                {data: 'status_id', name: 'status_id'},
                {data: 'title', name: 'title'},
                {data: 'created_at', name: 'created_at'},
                {data: 'updated_at', name: 'updated_at'},
                {data: 'action', name: 'action'}
            ]
        });
    });
</script>
@append