routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

/**
 * Public Routes
 */
Route::get('/', [
    'uses' => 'BlogController@index',
    'as'   => 'index',
]);

Route::get('/blog/{post}', [
    'uses' => 'BlogController@post',
    'as'   => 'blog.post',
    'middleware' => ['post.published'],
]);

Route::get('/blog/category/{category}', [
    'uses' => 'BlogController@category',
    'as'   => 'blog.category',
]);

Route::get('/blog/tag/{tag}', [
    'uses' => 'BlogController@tag',
    'as'   => 'blog.tag'
]);

Route::post('/blog/comment/{post}', [
    'uses' => 'BlogController@comment',
    'as'   => 'blog.comment'
]);

/**
 * Admin Routes
 */
Route::group([
    'namespace'  => '\\Admin',
    'middleware' => ['auth', 'admin.access'],
    'prefix'     => 'admin'
], function () {

    Route::group(['prefix' => 'posts'], function () {

        Route::get('/', [
            'uses' => 'PostController@index',
            'as'   => 'admin.posts.list'
        ]);

        Route::get('/create', [
            'uses' => 'PostController@create',
            'as'   => 'admin.posts.create'
        ]);

        Route::post('/', [
            'uses' => 'PostController@store',
            'as'   => 'admin.posts.store',
        ]);

        Route::get('/{post}', [
            'uses' => 'PostController@edit',
            'as'   => 'admin.posts.edit',
        ]);

        Route::patch('/{post}', [
            'uses' => 'PostController@update',
            'as'   => 'admin.posts.update',
        ]);

        Route::get('/{post}/remove', [
            'uses' => 'PostController@destroy',
            'as'   => 'admin.posts.remove',
        ]);

        Route::get('/{post}/publish', [
            'uses' => 'PostController@publish',
            'as'   => 'admin.posts.publish',
        ]);

        Route::get('/{post}/trash', [
            'uses' => 'PostController@trash',
            'as'   => 'admin.posts.trash',
        ]);

    });

    Route::group(['prefix' => 'categories'], function () {
        Route::get('/', [
            'uses' => 'CategoryController@index',
            'as'   => 'admin.categories.list',
        ]);

        Route::get('/create', [
            'uses' => 'CategoryController@create',
            'as'   => 'admin.categories.create',
        ]);

        Route::post('/', [
            'uses' => 'CategoryController@store',
            'as'   => 'admin.categories.store',
        ]);

        Route::get('/{category}', [
            'uses' => 'CategoryController@edit',
            'as'   => 'admin.categories.edit',
        ]);

        Route::patch('/{category}', [
            'uses' => 'CategoryController@update',
            'as'   => 'admin.categories.update',
        ]);

        Route::get('/{category}/remove', [
            'uses' => 'CategoryController@destroy',
            'as'   => 'admin.categories.remove',
        ]);
    });

    Route::group(['prefix' => 'tags'], function () {
        Route::get('/', [
            'uses' => 'TagController@index',
            'as'   => 'admin.tags.list',
        ]);

        Route::get('/create', [
            'uses' => 'TagController@create',
            'as'   => 'admin.tags.create',
        ]);

        Route::post('/', [
            'uses' => 'TagController@store',
            'as'   => 'admin.tags.store',
        ]);

        Route::get('/{tag}', [
            'uses' => 'TagController@edit',
            'as'   => 'admin.tags.edit',
        ]);

        Route::patch('/{tag}', [
            'uses' => 'TagController@update',
            'as'   => 'admin.tags.update',
        ]);

        Route::get('/{tag}/remove', [
            'uses' => 'TagController@destroy',
            'as'   => 'admin.tags.remove',
        ]);
    });

    Route::group(['prefix' => 'comments'], function () {
       Route::get('/', [
           'uses' => 'CommentController@index',
           'as'   => 'admin.comments.list',
       ]);

       Route::get('/{comment}/publish', [
           'uses' => 'CommentController@publish',
           'as'   => 'admin.comments.publish',
       ]);

       Route::get('/{comment}/spam', [
           'uses' => 'CommentController@spam',
           'as'   => 'admin.comments.spam',
       ]);

       Route::get('/{comment}/trash', [
           'uses' => 'CommentController@trash',
           'as'   => 'admin.comments.trash',
       ]);

       Route::get('/{comment}/remove', [
           'uses' => 'CommentController@destroy',
           'as'   => 'admin.comments.remove',
       ]);
    });
});

/**
 * API Routes
 */
Route::group([
    'namespace'  => '\\Api',
    'middleware' => [],
    'prefix'     => 'api',
], function () {

    Route::get('/posts', [
        'uses' => 'PostController@index',
        'as'   => 'api.posts.list'
    ]);

    Route::get('/categories', [
        'uses' => 'CategoryController@index',
        'as'   => 'api.categories.list',
    ]);

    Route::get('/tags', [
        'uses' => 'TagController@index',
        'as'   => 'api.tags.list',
    ]);

    Route::get('/comments', [
        'uses' => 'CommentController@index',
        'as'   => 'api.comments.list',
    ]);
});

app/Post.php
<?php

namespace App;

use App;
use App\Contracts\PostContract;
use App\Traits\HasStatus;
use App\Traits\TracksRecord;
use Illuminate\Database\Eloquent\Model;

/**
 * Class Post
 *
 * Core blog post model
 *
 * @package App
 */
class Post extends Model implements PostContract
{
    use HasStatus, TracksRecord;

    protected $fillable = ['status_id', 'title', 'slug', 'content', 'feature_label', 'video_link', 'publish_at', 'featured_image', 'gallery_images'];

    /**
     * Sets tablename for all child models
     *
     * @var string
     */
    protected $table = 'posts';

    /**
     * Defines fields expecting date objects
     *
     * @var array
     */
    protected $dates = ['created_at', 'updated_at', 'publish_at'];

    /**
     * Model events for setting type
     */
    protected static function boot()
    {
        parent::boot();

        static::creating(function (Post $post) {
            $post->type = get_class($post);
        });

        static::updating(function (Post $post) {
            $post->type = get_class($post);
        });
    }

    /**
     * Static function for returning a display type
     *
     * @return string
     */
    public function getTypeNameAttribute()
    {
        return 'Standard';
    }

    /**
     * Custom model override to support returning of different model types
     *
     * @param array $attributes
     * @param null $connection
     * @return static
     */
    public function newFromBuilder($attributes = [], $connection = null)
    {
        if (!isset($attributes->type)) {
            return parent::newFromBuilder($attributes, $connection);
        }

        $model = App::make($attributes->type)->newInstance([], true);
        $model->setRawAttributes((array) $attributes, true);
        $model->setConnection($connection ?: $this->connection);

        return $model;
    }

    /**
     * Override to set slug as route key for posts
     *
     * @return string
     */
    public function getRouteKeyName()
    {
        return 'slug';
    }

    /**
     * A blog can have many categtories
     *
     * @return \Illuminate\Database\Eloquent\Relations\BelongsToMany
     */
    public function categories()
    {
        return $this->belongsToMany('App\Category', 'post_categories', 'post_id', 'category_id');
    }

    /**
     * A blog can have many images
     *
     * @return \Illuminate\Database\Eloquent\Relations\BelongsToMany
     */
    public function images()
    {
        return $this->belongsToMany('App\Image', 'post_images')->withPivot('type', 'caption', 'ordinal');
    }

    /**
     * Posts may have many comments
     *
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function comments()
    {
        return $this->hasMany('App\Comment', 'post_id');
    }

    /**
     * A post can be associated with many tags
     *
     * @return \Illuminate\Database\Eloquent\Relations\BelongsToMany
     */
    public function tags()
    {
        return $this->belongsToMany('App\Tag', 'post_tags', 'post_id', 'tag_id');
    }

    /**
     * Returns a shortened content string
     *
     * @return string
     */
    public function getShortAttribute()
    {
        return str_limit(strip_tags($this->attributes['content']), 300);
    }

    /**
     * Returns a formatted display of the created date
     *
     * @return mixed
     */
    public function getDisplayDateAttribute()
    {
        return $this->created_at->format('M jS Y');
    }

    /**
     * Returns
     * @return string
     */
    public function getAuthorAttribute()
    {
        if (empty($this->createdBy)) {
            return 'Admin';
        }

        return $this->createdBy->name;
    }

    /**
     * Returns a count of post comments
     *
     * @return int
     */
    public function getCommentCountAttribute()
    {
        return $this->comments()->count();
    }

    /**
     * Returns additional validation rules for post type
     *
     * @return array
     */
    public function getValidationRules()
    {
        return [
            'featured_image' => 'required',
        ];
    }

    /**
     * Returns view for outputting feature
     *
     * @return string
     */
    public function getFeatureViewAttribute()
    {
        return 'includes.standard-post';
    }

    /**
     * Returns view for outputting feature summary
     * @return string
     */
    public function getFeatureShortViewAttribute()
    {
        return 'includes.standard-post-short';
    }
}

app/Http/Controllers/BlogController.php
<?php

namespace App\Http\Controllers;

use App\Category;
use App\Http\Requests\CommentRequest;
use App\Post;
use App\Repositories\PostRepository;
use App\Services\CommentManagerService;
use App\Tag;
use Auth;
use Session;

class BlogController extends Controller
{
    /**
     * @var CommentManagerService
     */
    protected $commentManager;

    /**
     * @var PostRepository
     */
    protected $postRepository;


    /**
     * BlogController constructor.
     *
     * @param CommentManagerService $commentManager
     * @param PostRepository $postRepository
     */
    public function __construct(CommentManagerService $commentManager, PostRepository $postRepository)
    {
        $this->commentManager = $commentManager;
        $this->postRepository = $postRepository;
    }

    /**
     * Displays a list of the most recent blog posts
     *
     * @return $this
     */
    public function index()
    {
        $posts = $this->postRepository->getRecentPosts();
        return view('blog.index')
            ->with('posts', $posts);
    }

    /**
     * Displays a detailed post
     *
     * @param Post $post
     * @return $this
     */
    public function post(Post $post)
    {
        $post->load(['comments.user', 'comments.status']);
        return view('blog.detail')
            ->with('post', $post);
    }

    /**
     * Displays a list of posts for the provided category
     *
     * @param Category $category
     * @return $this
     */
    public function category(Category $category)
    {
        $posts = $this->postRepository->getPostsByCategory($category);

        return view('blog.category')
            ->with('category', $category)
            ->with('posts', $posts);
    }

    /**
     * Displays a list of posts for the provided tag
     *
     * @param Tag $tag
     * @return $this
     */
    public function tag(Tag $tag)
    {
        $posts = $this->postRepository->getPostsByTag($tag);

        return view('blog.tag')
            ->with('tag', $tag)
            ->with('posts', $posts);
    }

    public function comment(CommentRequest $request, Post $post)
    {
        $userId = Auth::id();

        $this->commentManager->createComment($post, $request->all(), $userId);
        Session::flash('message', 'Comment Posted');
        return redirect()->route('blog.post', $post);
    }
}

resources/views/blog/category.blade.php
@extends('layouts.master')

@section('page-title', $category->name)

@section('headline', $category->name)

@section('content')
    @foreach ($posts as $post)
        @include('includes.post-summary', ['post' => $post])
    @endforeach
@append

resources/views/blog/detail.blade.php
@extends('layouts.master')

@section('page-title', $post->title)

@section('headline', $post->title)

@section('content')
    <div id="main-blog-single">
        <div class="content">
            <div>
                <div class="row">
                    <div class="blog-main col-sm-8">
                        @include($post->feature_view, ['post' => $post])
                    </div>
                    @include('includes.blog-bar', ['post' => $post])
                    <div class="post-content">
                        {!! $post->content !!}
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div><hr/></div>
    @if ($post->comments->where('status.code', 'published')->count() > 0)
        <div class="row">
            <h3>Comments</h3>
            <br/>
            <br/>
            @foreach($post->comments->where('status.code', 'published') as $comment)
                <div class="comment">
                    @if (!empty($comment->user))
                        <h4>{{ $comment->user->name }}</h4>
                    @else
                        <h4>{{ $comment->name }}</h4>
                    @endif
                    <small>{{ $comment->created_at->format('F jS Y') }}</small>
                    <hr/>
                    <p>{{ $comment->content }}</p>
                </div>
            @endforeach
        </div>
    @endif
    <div><hr/></div>
    <div class="row">
        {!! Form::open(['url' => route('blog.comment', $post), 'class' => 'form', 'role' => 'form', 'method' => 'post']) !!}
            @if(auth()->check())
                Logged in as {{ auth()->user()->name }}<br />
            @else
                {!! Form::textField('email', 'Email') !!}
                {!! Form::textField('name', 'Name') !!}
            @endif
            <h3>Comment</h3>
            {!! Form::textarea('content', null, ['class' => 'form-control']) !!}
            <button type="submit" class="btn btn-primary btn-addon">
                <i class="fa fa-save"></i> Leave Comment
            </button>
        {!! Form::close() !!}
    </div>
@append

resources/views/blog/index.blade.php
@extends('layouts.master')

@section('page-title', 'Posts')

@section('headline', 'Posts')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-9">
                @foreach ($posts as $post)
                    @include('includes.post-summary', ['post' => $post])
                @endforeach
            </div>
            <div class="col-md-3">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        Categories
                    </div>
                    <div class="panel-body">
                        @foreach($categories as $category)
                            <a href="{{ route('blog.category', $category) }}">{{ $category->name }}</a><br />
                        @endforeach
                    </div>
                </div>
                <div class="panel panel-default">
                    <div class="panel-heading">
                        Recent Posts
                    </div>
                    <div class="panel-body">
                        @foreach($recentPosts as $post)
                            <a href="{{ route('blog.post', $post) }}">{{ $post->title }}</a><br />
                        @endforeach
                    </div>
                </div>
                <div class="panel panel-default">
                    <div class="panel-heading">
                        Tags
                    </div>
                    <div class="panel-body">
                        @foreach($tags as $tag)
                            <a href="{{ route('blog.tag', $tag) }}">{{ $tag->name }}</a><br />
                        @endforeach
                    </div>
                </div>
            </div>
        </div>
    </div>

@append

resources/views/blog/tag.blade.php
@extends('layouts.master')

@section('page-title', $tag->name)

@section('headline', $tag->name)

@section('content')
    @foreach ($posts as $post)
        @include('includes.post-summary', ['post' => $post])
    @endforeach
@append