routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

/**
 * Public Routes
 */
Route::get('/', [
    'uses' => 'BlogController@index',
    'as'   => 'index',
]);

Route::get('/blog/{post}', [
    'uses' => 'BlogController@post',
    'as'   => 'blog.post',
    'middleware' => ['post.published'],
]);

Route::get('/blog/category/{category}', [
    'uses' => 'BlogController@category',
    'as'   => 'blog.category',
]);

Route::get('/blog/tag/{tag}', [
    'uses' => 'BlogController@tag',
    'as'   => 'blog.tag'
]);

Route::post('/blog/comment/{post}', [
    'uses' => 'BlogController@comment',
    'as'   => 'blog.comment'
]);

/**
 * Admin Routes
 */
Route::group([
    'namespace'  => '\\Admin',
    'middleware' => ['auth', 'admin.access'],
    'prefix'     => 'admin'
], function () {

    Route::group(['prefix' => 'posts'], function () {

        Route::get('/', [
            'uses' => 'PostController@index',
            'as'   => 'admin.posts.list'
        ]);

        Route::get('/create', [
            'uses' => 'PostController@create',
            'as'   => 'admin.posts.create'
        ]);

        Route::post('/', [
            'uses' => 'PostController@store',
            'as'   => 'admin.posts.store',
        ]);

        Route::get('/{post}', [
            'uses' => 'PostController@edit',
            'as'   => 'admin.posts.edit',
        ]);

        Route::patch('/{post}', [
            'uses' => 'PostController@update',
            'as'   => 'admin.posts.update',
        ]);

        Route::get('/{post}/remove', [
            'uses' => 'PostController@destroy',
            'as'   => 'admin.posts.remove',
        ]);

        Route::get('/{post}/publish', [
            'uses' => 'PostController@publish',
            'as'   => 'admin.posts.publish',
        ]);

        Route::get('/{post}/trash', [
            'uses' => 'PostController@trash',
            'as'   => 'admin.posts.trash',
        ]);

    });

    Route::group(['prefix' => 'categories'], function () {
        Route::get('/', [
            'uses' => 'CategoryController@index',
            'as'   => 'admin.categories.list',
        ]);

        Route::get('/create', [
            'uses' => 'CategoryController@create',
            'as'   => 'admin.categories.create',
        ]);

        Route::post('/', [
            'uses' => 'CategoryController@store',
            'as'   => 'admin.categories.store',
        ]);

        Route::get('/{category}', [
            'uses' => 'CategoryController@edit',
            'as'   => 'admin.categories.edit',
        ]);

        Route::patch('/{category}', [
            'uses' => 'CategoryController@update',
            'as'   => 'admin.categories.update',
        ]);

        Route::get('/{category}/remove', [
            'uses' => 'CategoryController@destroy',
            'as'   => 'admin.categories.remove',
        ]);
    });

    Route::group(['prefix' => 'tags'], function () {
        Route::get('/', [
            'uses' => 'TagController@index',
            'as'   => 'admin.tags.list',
        ]);

        Route::get('/create', [
            'uses' => 'TagController@create',
            'as'   => 'admin.tags.create',
        ]);

        Route::post('/', [
            'uses' => 'TagController@store',
            'as'   => 'admin.tags.store',
        ]);

        Route::get('/{tag}', [
            'uses' => 'TagController@edit',
            'as'   => 'admin.tags.edit',
        ]);

        Route::patch('/{tag}', [
            'uses' => 'TagController@update',
            'as'   => 'admin.tags.update',
        ]);

        Route::get('/{tag}/remove', [
            'uses' => 'TagController@destroy',
            'as'   => 'admin.tags.remove',
        ]);
    });

    Route::group(['prefix' => 'comments'], function () {
       Route::get('/', [
           'uses' => 'CommentController@index',
           'as'   => 'admin.comments.list',
       ]);

       Route::get('/{comment}/publish', [
           'uses' => 'CommentController@publish',
           'as'   => 'admin.comments.publish',
       ]);

       Route::get('/{comment}/spam', [
           'uses' => 'CommentController@spam',
           'as'   => 'admin.comments.spam',
       ]);

       Route::get('/{comment}/trash', [
           'uses' => 'CommentController@trash',
           'as'   => 'admin.comments.trash',
       ]);

       Route::get('/{comment}/remove', [
           'uses' => 'CommentController@destroy',
           'as'   => 'admin.comments.remove',
       ]);
    });
});

/**
 * API Routes
 */
Route::group([
    'namespace'  => '\\Api',
    'middleware' => [],
    'prefix'     => 'api',
], function () {

    Route::get('/posts', [
        'uses' => 'PostController@index',
        'as'   => 'api.posts.list'
    ]);

    Route::get('/categories', [
        'uses' => 'CategoryController@index',
        'as'   => 'api.categories.list',
    ]);

    Route::get('/tags', [
        'uses' => 'TagController@index',
        'as'   => 'api.tags.list',
    ]);

    Route::get('/comments', [
        'uses' => 'CommentController@index',
        'as'   => 'api.comments.list',
    ]);
});

app/Post.php
<?php

namespace App;

use App;
use App\Contracts\PostContract;
use App\Traits\HasStatus;
use App\Traits\TracksRecord;
use Illuminate\Database\Eloquent\Model;

/**
 * Class Post
 *
 * Core blog post model
 *
 * @package App
 */
class Post extends Model implements PostContract
{
    use HasStatus, TracksRecord;

    protected $fillable = ['status_id', 'title', 'slug', 'content', 'feature_label', 'video_link', 'publish_at', 'featured_image', 'gallery_images'];

    /**
     * Sets tablename for all child models
     *
     * @var string
     */
    protected $table = 'posts';

    /**
     * Defines fields expecting date objects
     *
     * @var array
     */
    protected $dates = ['created_at', 'updated_at', 'publish_at'];

    /**
     * Model events for setting type
     */
    protected static function boot()
    {
        parent::boot();

        static::creating(function (Post $post) {
            $post->type = get_class($post);
        });

        static::updating(function (Post $post) {
            $post->type = get_class($post);
        });
    }

    /**
     * Static function for returning a display type
     *
     * @return string
     */
    public function getTypeNameAttribute()
    {
        return 'Standard';
    }

    /**
     * Custom model override to support returning of different model types
     *
     * @param array $attributes
     * @param null $connection
     * @return static
     */
    public function newFromBuilder($attributes = [], $connection = null)
    {
        if (!isset($attributes->type)) {
            return parent::newFromBuilder($attributes, $connection);
        }

        $model = App::make($attributes->type)->newInstance([], true);
        $model->setRawAttributes((array) $attributes, true);
        $model->setConnection($connection ?: $this->connection);

        return $model;
    }

    /**
     * Override to set slug as route key for posts
     *
     * @return string
     */
    public function getRouteKeyName()
    {
        return 'slug';
    }

    /**
     * A blog can have many categtories
     *
     * @return \Illuminate\Database\Eloquent\Relations\BelongsToMany
     */
    public function categories()
    {
        return $this->belongsToMany('App\Category', 'post_categories', 'post_id', 'category_id');
    }

    /**
     * A blog can have many images
     *
     * @return \Illuminate\Database\Eloquent\Relations\BelongsToMany
     */
    public function images()
    {
        return $this->belongsToMany('App\Image', 'post_images')->withPivot('type', 'caption', 'ordinal');
    }

    /**
     * Posts may have many comments
     *
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function comments()
    {
        return $this->hasMany('App\Comment', 'post_id');
    }

    /**
     * A post can be associated with many tags
     *
     * @return \Illuminate\Database\Eloquent\Relations\BelongsToMany
     */
    public function tags()
    {
        return $this->belongsToMany('App\Tag', 'post_tags', 'post_id', 'tag_id');
    }

    /**
     * Returns a shortened content string
     *
     * @return string
     */
    public function getShortAttribute()
    {
        return str_limit(strip_tags($this->attributes['content']), 300);
    }

    /**
     * Returns a formatted display of the created date
     *
     * @return mixed
     */
    public function getDisplayDateAttribute()
    {
        return $this->created_at->format('M jS Y');
    }

    /**
     * Returns
     * @return string
     */
    public function getAuthorAttribute()
    {
        if (empty($this->createdBy)) {
            return 'Admin';
        }

        return $this->createdBy->name;
    }

    /**
     * Returns a count of post comments
     *
     * @return int
     */
    public function getCommentCountAttribute()
    {
        return $this->comments()->count();
    }

    /**
     * Returns additional validation rules for post type
     *
     * @return array
     */
    public function getValidationRules()
    {
        return [
            'featured_image' => 'required',
        ];
    }

    /**
     * Returns view for outputting feature
     *
     * @return string
     */
    public function getFeatureViewAttribute()
    {
        return 'includes.standard-post';
    }

    /**
     * Returns view for outputting feature summary
     * @return string
     */
    public function getFeatureShortViewAttribute()
    {
        return 'includes.standard-post-short';
    }
}

resources/views/includes/blog-bar.blade.php
<div class="blog-bottom-info">
    <ul>
        <li>
            <i class="fa fa-calendar"></i>
            <a href="{{ route('blog.post', $post) }}">{{ $post->displayDate }}</a>
        </li>
        <li>
            <i class="fa fa-comments"></i>
            {{ $post->commentCount }} Comments
        </li>
        <li>
            <i class="fa fa-tags"></i>
        </li>
    </ul>
    <div id="post-author">
        <i class="fa fa-pencil"></i>
        By {{ $post->author }}
    </div>
</div>

resources/views/includes/form-messages.blade.php
@if(isset($errors) && $errors->any())
    <div class="alert alert-warning">
        @foreach ($errors->all('<p>:message</p>') as $message)
            {!! $message !!}
        @endforeach
    </div>
@endif

resources/views/includes/gallery-post.blade.php
<div class="blog-main-image gallery-out">
    <div class="single-post-format">
        @foreach($post->gallery_images as $image)
            <div class="responsive">
                <div class="gallery">
                    <a target="_blank" href="{{ url($image) }}">
                        <img src="{{ url($image) }}" />
                    </a>
                </div>
            </div>
        @endforeach
    </div>
</div><br/>
<br/>

resources/views/includes/messages.blade.php
{{--
===================
GLOBAL SITE MESSAGE
===================
@todo Blow this out to allow for message types
info, warning, danger, etc.
--}}
@if(app('session')->has('message'))
    <div class="global-message alert alert-info alert-dismissable fade in fade-in" role="alert">
        <button type="button" class="close" data-dismiss="alert">
            <span aria-hidden="true">&times;</span>
            <span class="sr-only">Close</span>
        </button>
        {{ session('message') }}
    </div>
@elseif(app('session')->has('message-success'))
    <div class="global-message alert alert-success alert-dismissable fade in fade-in" role="alert">
        <button type="button" class="close" data-dismiss="alert">
            <span aria-hidden="true">&times;</span>
            <span class="sr-only">Close</span>
        </button>
        {{ session('message-success') }}
    </div>
@endif

resources/views/includes/post-summary.blade.php
<div class="row">
    <div class="blog-main col-sm-8">
        <div class="blog-cats-list">
            <div class="image">
                @include($post->feature_short_view)
            </div>
            <h3><a href="{{ route('blog.post', $post) }}">{{ $post->title }}</a></h3>
            @include('includes.blog-bar', ['post' => $post])
            {!! $post->short !!}
            <br />
            <hr />
        </div>
    </div>
</div>

resources/views/includes/standard-post-short.blade.php
@if ($post->featured_image != null)
    <div class="blog-main-image">
        <div class="single-post-format">
            <img src="{{ url($post->featured_image) }}" class="attachment-full size-full wp-post-image"/>
        </div>
    </div>
@endif

resources/views/includes/standard-post.blade.php
<div class="blog-main-image">
    <div class="single-post-format">
        <img src="{{ url($post->featured_image) }}" class="attachment-full size-full wp-post-image"/>
    </div>
</div>

resources/views/includes/video-post.blade.php
<div class="blog-main-image">
    <div class="single-post-format">
        {!! \Merujan99\LaravelVideoEmbed\Facades\LaravelVideoEmbed::parse($post->video_link, config('video.whitelist'), config('video.params')) !!}
    </div>
</div>